Repository ROBOTIS-GIT/OpenCR, pull requests merged in 2018-05, with the labels that each got.

#90 digitalWriteFast and digitalReadFast
  arduino/opencr_arduino/opencr/cores/arduino/Arduino.h
  arduino/opencr_arduino/opencr/cores/arduino/digitalWriteFast.h
Labels: enhancement, in progress

#84 add CAN C++ lib
  arduino/opencr_arduino/opencr/libraries/CAN/bsp_can.cpp
  arduino/opencr_arduino/opencr/libraries/CAN/bsp_can.h
Labels: enhancement, waiting for reply

#94 SPI_HAS_TRANSACTION support
  arduino/opencr_arduino/opencr/libraries/SPI/SPI.cpp
  arduino/opencr_arduino/opencr/libraries/SPI/SPI.h
  arduino/opencr_arduino/opencr/libraries/SPI/keywords.txt
Labels: enhancement, in progress

#99 hotfix for travis target branch
  install.sh
Labels: in progress
